{
 "title": "{environment} Worker Roles",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DataSource",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": "questsit,Default-ServiceBus-WestUS"
   },
   { "name": "ResourceName", "label": "Resource Name", "query": "questsit-prem,omnius-prem" }
  ]
 },
 "panels": [
  {
   "title": "Worker Roles - Max CPU / Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "count"
      ],
      "aggregation": "max",
      "alias": "Processor - {{groupbyvalue}}",
      "groupBy": "customDimensions/QueueName",
      "groupByOptions": [
       "performanceCounter/name",
       "performanceCounter/category",
       "performanceCounter/counter",
       "performanceCounter/instance",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/QueueName"
      ],
      "metricName": "performanceCounters/processorCpuPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrain": "1",
      "timeGrainType": "specific",
      "timeGrainUnit": "minute",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f79b2607-d524-41e9-8812-b708a31e0469"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Worker Roles - Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "count"
      ],
      "aggregation": "min",
      "alias": "{{groupbyvalue}}",
      "groupBy": "customDimensions/QueueName",
      "groupByOptions": [
       "performanceCounter/name",
       "performanceCounter/category",
       "performanceCounter/counter",
       "performanceCounter/instance",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/QueueName"
      ],
      "metricName": "performanceCounters/memoryAvailableBytes",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f79b2607-d524-41e9-8812-b708a31e0469"
     },
     "azureMonitor": {
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "questsit",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    },
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "count"
      ],
      "aggregation": "max",
      "alias": "Max Memory - {{groupbyvalue}}",
      "groupBy": "customDimensions/QueueName",
      "groupByOptions": [
       "performanceCounter/name",
       "performanceCounter/category",
       "performanceCounter/counter",
       "performanceCounter/instance",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/QueueName"
      ],
      "metricName": "performanceCounters/processPrivateBytes",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f79b2607-d524-41e9-8812-b708a31e0469"
     },
     "azureMonitor": {
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "questsit",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Worker Roles - Dependencies Duration / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "sum",
      "alias": "{{groupbyvalue}}",
      "groupBy": "customDimensions/QueueName",
      "groupByOptions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/QueueName"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrain": "1",
      "timeGrainType": "specific",
      "timeGrainUnit": "minute",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f79b2607-d524-41e9-8812-b708a31e0469"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Worker Roles - Exceptions / Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "count"
      ],
      "aggregation": "max",
      "alias": "Exceptions - {{groupbyvalue}}",
      "groupBy": "customDimensions/QueueName",
      "groupByOptions": [
       "performanceCounter/name",
       "performanceCounter/category",
       "performanceCounter/counter",
       "performanceCounter/instance",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/QueueName"
      ],
      "metricName": "performanceCounters/exceptionsPerSecond",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrain": "1",
      "timeGrainType": "specific",
      "timeGrainUnit": "minute",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f79b2607-d524-41e9-8812-b708a31e0469"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Service Bus - Requests",
   "type": "graph",
   "description": "Average Message in Queue / minute",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "502a68d4-d9e2-4132-8be8-b73119eb3361"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Dead-letter Queue - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "SuccessfulRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "omnius-prem",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "502a68d4-d9e2-4132-8be8-b73119eb3361"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Requests - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "omnius-prem",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Service Bus - Outgoing Messages",
   "type": "table",
   "description": "Average Message in Queue / minute",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "502a68d4-d9e2-4132-8be8-b73119eb3361"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "OutgoingMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "omnius-prem",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}